source 'http://rubygems.org'

# dependencies are generated using a strict version, don't forget to edit the dependency versions when upgrading.
merb_gems_version = "1.1.3"
merb_auth_version = "1.1.1"

# If you did disable json for Merb, comment out this line.
# If you want use json gem just change it.
# Don't use json gem version lower than 1.1.7! Older versions has security bug!
gem "json_pure", ">= 1.1.7", :require => "json"
gem "merb-assets", merb_gems_version
gem "merb-auth", merb_auth_version
gem "merb-auth-core", merb_auth_version
gem "merb-auth-more", merb_auth_version
gem "merb-auth-slice-password", merb_auth_version
gem "merb-cache", merb_gems_version
gem "merb-core", merb_gems_version
gem "merb-exceptions", merb_gems_version
gem "merb-gen", merb_gems_version
gem "merb-haml", merb_gems_version
gem "merb-helpers", merb_gems_version
gem "merb-mailer", merb_gems_version
gem "merb-param-protection", merb_gems_version
gem "merb-slices", merb_gems_version

gem "merb_sequel"
gem "sqlite3-ruby", "1.2.5"

gem 'tlsmail'

group :development, :test do
  gem "webrat"
  gem "ruby-debug"
  gem "rspec", "<2.0.0"
  gem "mongrel"
  gem 'capistrano', :require => nil
  gem 'capistrano-ext', :require => nil
end


