# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development: &defaults
  adapter: sqlite
  database: ankieter_development.db

test:
  adapter: sqlite
  database: ankieter_test.db

rake:
  <<: *defaults
